// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD967Q0fDYWFVhhO6U954M95BRiFqmVH3Q',
    appId: '1:82802464653:android:4c351634a4954af0888fc4',
    messagingSenderId: '82802464653',
    projectId: 'chat-app-fliutter',
    storageBucket: 'chat-app-fliutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlJp3bzwkum7GwOOJugor4g4Chm2xnTQY',
    appId: '1:82802464653:ios:43b4f9464d26fd70888fc4',
    messagingSenderId: '82802464653',
    projectId: 'chat-app-fliutter',
    storageBucket: 'chat-app-fliutter.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVYUWPilkQICTVfIfb3GYO7WKSdQQOto',
    appId: '1:82802464653:web:40832b7fb31e3b18888fc4',
    messagingSenderId: '82802464653',
    projectId: 'chat-app-fliutter',
    authDomain: 'chat-app-fliutter.firebaseapp.com',
    storageBucket: 'chat-app-fliutter.appspot.com',
  );

}